Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 1, in <module>
    import dgl.function as fn
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/__init__.py", line 14, in <module>
    from .backend import backend_name, load_backend  # usort: skip
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/backend/__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/backend/__init__.py", line 57, in load_backend
    mod = importlib.import_module(".%s" % mod_name, __name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/backend/pytorch/__init__.py", line 1, in <module>
    from .sparse import *
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/backend/pytorch/sparse.py", line 24, in <module>
    from ...heterograph_index import create_unitgraph_from_csr
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/heterograph_index.py", line 13, in <module>
    from ._ffi.streams import to_dgl_stream_handle
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 72, in __init__
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 1, in <module>
    import dgl.function as fn
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/distributed/dist_graph.py", line 37, in <module>
    from .partition import (
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/distributed/partition.py", line 13, in <module>
    from ..data.utils import load_graphs, load_tensors, save_graphs, save_tensors
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/__init__.py", line 7, in <module>
    from . import citation_graph as citegrh
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/citation_graph.py", line 19, in <module>
    from .dgl_dataset import DGLBuiltinDataset
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/dgl_dataset.py", line 12, in <module>
    from .utils import download, extract_archive, get_download_dir, makedirs
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/utils.py", line 14, in <module>
    import requests
  File "/home/yannick/.local/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 12, in <module>
    from .connection import (
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 15, in <module>
    from .util.proxy import create_proxy_ssl_context
  File "/usr/lib/python3/dist-packages/urllib3/util/__init__.py", line 8, in <module>
    from .ssl_ import (
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 17, in <module>
    from .url import BRACELESS_IPV6_ADDRZ_RE, IPV4_RE
  File "/usr/lib/python3/dist-packages/urllib3/util/url.py", line 62, in <module>
    IPV6_ADDRZ_RE = re.compile("^" + IPV6_ADDRZ_PAT + "$")
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 792, in compile
    code = _code(p, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 631, in _code
    _compile(code, p.data, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 225, in _compile
    _compile(code, av, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 225, in _compile
    _compile(code, av, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 164, in _compile
    _compile(code, av[2], flags)
  File "/usr/lib/python3.10/sre_compile.py", line 136, in _compile
    charset, hascased = _optimize_charset(av, iscased, tolower, fixes)
  File "/usr/lib/python3.10/sre_compile.py", line 355, in _optimize_charset
    break
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
Traceback (most recent call last):
  File "/home/yannick/Documents/Acoustic_Linguistic_GNN/gnn_model.py", line 256, in <module>
    glist, label_dict = load_graphs(os.path.join(input_folder,graph_file))
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 186, in load_graphs
    check_local_file_exists(filename)
  File "/home/yannick/.local/lib/python3.10/site-packages/dgl/data/graph_serialize.py", line 40, in check_local_file_exists
    raise DGLError("File {} does not exist.".format(filename))
dgl._ffi.base.DGLError: File saved_graphs/google_command/clique/filter/kws_graph_11_1_100.dgl does not exist.
1612
8
Epoch 0, Loss: 3.4573376178741455, Accuracy: 13.75%
Epoch 10, Loss: 1.186966896057129, Accuracy: 63.75%
Epoch 20, Loss: 0.5956915616989136, Accuracy: 83.75%
Epoch 30, Loss: 0.2064174860715866, Accuracy: 97.50%
Epoch 40, Loss: 0.052635520696640015, Accuracy: 100.00%
Epoch 0, Loss: 0.7221173644065857, Accuracy: 13.75%
Epoch 10, Loss: 0.11231371760368347, Accuracy: 17.50%
Epoch 20, Loss: 0.06435683369636536, Accuracy: 13.75%
Epoch 30, Loss: 0.05118466541171074, Accuracy: 16.25%
Epoch 40, Loss: 0.0425981730222702, Accuracy: 17.50%
Epoch 0, Loss: 7.903047561645508, Accuracy: 11.25%
Epoch 10, Loss: 3.0915584564208984, Accuracy: 12.50%
Epoch 20, Loss: 3.05591082572937, Accuracy: 12.50%
Epoch 30, Loss: 3.044696569442749, Accuracy: 12.50%
Epoch 40, Loss: 3.0458219051361084, Accuracy: 12.50%
1612
8
Epoch 0, Loss: 4.427796840667725, Accuracy: 10.00%
Epoch 10, Loss: 1.5177524089813232, Accuracy: 41.25%
Epoch 20, Loss: 0.9073605537414551, Accuracy: 68.75%
Epoch 30, Loss: 0.516348659992218, Accuracy: 86.25%
Epoch 40, Loss: 0.2507181763648987, Accuracy: 97.50%
Epoch 0, Loss: 0.7994305491447449, Accuracy: 3.75%
Epoch 10, Loss: 0.13252782821655273, Accuracy: 15.00%
Epoch 20, Loss: 0.06529345363378525, Accuracy: 21.25%
Epoch 30, Loss: 0.05399659648537636, Accuracy: 15.00%
Epoch 40, Loss: 0.04833551496267319, Accuracy: 17.50%
Epoch 0, Loss: 3.964995861053467, Accuracy: 17.50%
Epoch 10, Loss: 7.053064346313477, Accuracy: 12.50%
Epoch 20, Loss: 5.393588542938232, Accuracy: 12.50%
Epoch 30, Loss: 5.371744155883789, Accuracy: 12.50%
Epoch 40, Loss: 5.370887756347656, Accuracy: 12.50%
